version: '3'

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "7070:6060"
    links:
      - mongo
  mongo:
    container_name: mongodatabase
    image: mongo
    ports:
      - "27018:27017"